### PR TITLE
feat: allow to delete duplicated assets #24

### LINKED ISSUE #24: Expected behaviour for second asset upload
Assuming `reuseRelease: true`, what is the expected behaviour of running release twice? At the moment the message `Uploading asset MyApp.zip` is displayed but the asset is not actually uploaded or replaced the second time the program runs. 

I think this should *replace* the assets with the same name, eventually with a parameter to disable this behaviour and throw an error instead.

### PR DESCRIPTION
**Pull request by marceloavf**
- [x] Check for duplicated asset and remove it
- [x] Restart upload for this deleted asset
- [x] Property to allow/deny deleting duplicate assets
- [x] Adjust CLI 

Will resolve #24

### CODE REVIEW

**Comment by marceloavf** [comment]
I think this should be a breaking change, since `--skipDuplicatedAssets` can break someone who don't know that the plugin isn't replacing the assets

**Comment by aluxian** [comment]
Wow, good job

**Comment by aluxian** [comment]
Thank you!

**Comment by aluxian** [comment]
I released this as 1.4.0

**Pull request merged**
