### PR TITLE
Throw an error if assets can't be resolved. Fixes #4

### LINKED ISSUE #4: Don't publish release if assets are not available
Check before creating a release that all the assets are ready, and if not raise an error.

### PR DESCRIPTION
**Pull request by jonboiser**
I think this the minimal change to fix #4. I tried to examine #11 and see if I could fix the conflicts, but so much of the changes were stylistic, so I just started from scratch.

I did some manual testing and it seems to be okay. One thing with the CLI is that it fails pretty late in the game (after setting up the request and authorizing), but thought refactoring that might be something that can be done later.

### CODE REVIEW

**Comment by Aluxian** [comment]
To move the checks earlier in the CLI workflow, do you think adding the checks [here](https://github.com/jonboiser/publish-release/blob/7e8954f0129b2c41e9b5c40798343ad90e6c4cc3/bin/publish-release#L149) would suffice? We could then append a parameter `skipFileChecks` so that they're not checked for twice.

**Comment by jonboiser** [comment]
When I was trying out the CLI, I kind of wish it would fail before I needed to set the tag, login, etc. I tried putting in a similar code [here](https://github.com/jonboiser/publish-release/blob/7e8954f0129b2c41e9b5c40798343ad90e6c4cc3/bin/publish-release#L38) after `argv` was read in, but didn't really like how the error messages were coming out.

**Comment by jonboiser** [comment]
If we did expose a `skipFileChecks` parameter for the module API, that might be something users could set too, if they really wanted to.

**Comment by Aluxian** [comment]
Well, whether we place it where I suggested (before auth) or where you suggested (after argv), it's the same thing because the code inbetween is just definitions. What did the error messages look like and why didn't you like them? Shouldn't it just show `missing asset: ...`?

**Comment by jonboiser** [comment]
It showed the error, plus the stack trace. I forget the exact code but it was basically this. so you'll see the error, then the stack trace right after, which seemed ugly to me.

```
try {
  accessSync etc...
} catch(err) {
  throw new Error("missing asset")
}
```

**Comment by Aluxian** [comment]
All right, I'll take a look and then merge it. Thank you very much for helping this project :)

--
Alexandru Rosianu Full-Stack Developer aluxian.com | startersquad.com On Thu, May 19, 2016 at 10:25 PM, Jonathan Boiser < notifications@github.com [notifications@github.com] > wrote:
It showed the error, plus the stack trace. I forget the exact code but it was basically this. so you'll see the error, then the stack trace right after, which seemed ugly to me.

try {
  accessSync etc...
} catch(err) {
  throw new Error("missing asset")
}

**Comment by jonboiser** [comment]
My pleasure. The module works great for me. I probably wouldn't use the CLI much, but can see how having it fail faster would be better UX. I can take a look at it later and maybe try to contribute some tests.

**Comment by Aluxian** [comment]
Merged and added for CLI too. Give it a quick try if you have time :)

**Pull request merged**
